/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VoluntariosIndexRouteImport } from './routes/voluntarios/index'
import { Route as TestIndexRouteImport } from './routes/test/index'
import { Route as ProyectosIndexRouteImport } from './routes/proyectos/index'
import { Route as DonarIndexRouteImport } from './routes/donar/index'
import { Route as DonacionesIndexRouteImport } from './routes/donaciones/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VoluntariosIndexRoute = VoluntariosIndexRouteImport.update({
  id: '/voluntarios/',
  path: '/voluntarios/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestIndexRoute = TestIndexRouteImport.update({
  id: '/test/',
  path: '/test/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectosIndexRoute = ProyectosIndexRouteImport.update({
  id: '/proyectos/',
  path: '/proyectos/',
  getParentRoute: () => rootRouteImport,
} as any)
const DonarIndexRoute = DonarIndexRouteImport.update({
  id: '/donar/',
  path: '/donar/',
  getParentRoute: () => rootRouteImport,
} as any)
const DonacionesIndexRoute = DonacionesIndexRouteImport.update({
  id: '/donaciones/',
  path: '/donaciones/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/donaciones': typeof DonacionesIndexRoute
  '/donar': typeof DonarIndexRoute
  '/proyectos': typeof ProyectosIndexRoute
  '/test': typeof TestIndexRoute
  '/voluntarios': typeof VoluntariosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/donaciones': typeof DonacionesIndexRoute
  '/donar': typeof DonarIndexRoute
  '/proyectos': typeof ProyectosIndexRoute
  '/test': typeof TestIndexRoute
  '/voluntarios': typeof VoluntariosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/donaciones/': typeof DonacionesIndexRoute
  '/donar/': typeof DonarIndexRoute
  '/proyectos/': typeof ProyectosIndexRoute
  '/test/': typeof TestIndexRoute
  '/voluntarios/': typeof VoluntariosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/donaciones'
    | '/donar'
    | '/proyectos'
    | '/test'
    | '/voluntarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/donaciones'
    | '/donar'
    | '/proyectos'
    | '/test'
    | '/voluntarios'
  id:
    | '__root__'
    | '/'
    | '/admin/'
    | '/dashboard/'
    | '/donaciones/'
    | '/donar/'
    | '/proyectos/'
    | '/test/'
    | '/voluntarios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DonacionesIndexRoute: typeof DonacionesIndexRoute
  DonarIndexRoute: typeof DonarIndexRoute
  ProyectosIndexRoute: typeof ProyectosIndexRoute
  TestIndexRoute: typeof TestIndexRoute
  VoluntariosIndexRoute: typeof VoluntariosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voluntarios/': {
      id: '/voluntarios/'
      path: '/voluntarios'
      fullPath: '/voluntarios'
      preLoaderRoute: typeof VoluntariosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/': {
      id: '/test/'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyectos/': {
      id: '/proyectos/'
      path: '/proyectos'
      fullPath: '/proyectos'
      preLoaderRoute: typeof ProyectosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donar/': {
      id: '/donar/'
      path: '/donar'
      fullPath: '/donar'
      preLoaderRoute: typeof DonarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donaciones/': {
      id: '/donaciones/'
      path: '/donaciones'
      fullPath: '/donaciones'
      preLoaderRoute: typeof DonacionesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DonacionesIndexRoute: DonacionesIndexRoute,
  DonarIndexRoute: DonarIndexRoute,
  ProyectosIndexRoute: ProyectosIndexRoute,
  TestIndexRoute: TestIndexRoute,
  VoluntariosIndexRoute: VoluntariosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
